Add CI/CD pipeline 29

diff --git a/.github/workflows/ci_cd_pipeline.yml b/.github/workflows/ci_cd_pipeline.yml
--- a/.github/workflows/ci_cd_pipeline.yml
+++ b/.github/workflows/ci_cd_pipeline.yml
@@ -41,8 +41,10 @@ jobs:
           echo "${{ secrets.AZURE_PASSWORD }}" | docker login x23173394k8scontainerregistry.azurecr.io -u "${{ secrets.AZURE_USERNAME }}" --password-stdin
           docker push x23173394k8scontainerregistry.azurecr.io/kubernetes-security-framework:${{ env.TAG }}
 
-      - name: Pull Docker Image
-        run: docker pull x23173394k8scontainerregistry.azurecr.io/kubernetes-security-framework:${{ env.TAG }}
+      - name: Pull and Validate Docker Image
+        run: |
+          docker pull x23173394k8scontainerregistry.azurecr.io/kubernetes-security-framework:${{ env.TAG }}
+          docker run --rm --entrypoint bash x23173394k8scontainerregistry.azurecr.io/kubernetes-security-framework:${{ env.TAG }} -c "dpkg-query -W" || echo "Failed to retrieve installed packages. Please check the base image."
 
       - name: Update Deployment YAML with New Image Tag
         run: |
